### ISSUE TITLE
Last row is not shown

### ISSUE THREAD

**Issue by sgup** [ayooby/react-native-calendar-heatmap#10]
only shows 6 days in the week instead of 7, height function is broken.

**Comment by kuraydev** [comment]
Oww, I missed it. Thank you so much :) I'm gonna work on it this week

**Comment by sgup** [comment]
awesome, thanks! Also noticed:

The component adjusts to width, but cuts off from the end, rather than the beginning. So smaller screens would get the most recent dates cut off :/

**Comment by kuraydev** [comment]
Okay, I noted that I have a plan to make a re-write it again with a modern way.

**Comment by kuraydev** [comment]
Thank you @juulieen :)
New version: 0.2.3
