### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by frankfaustino** [ayooby/react-native-calendar-heatmap#2]
I tried installing your react-native-calendar-heatmap via npm install & yarn add, and I get the following error message:

`npm ERR! 404 Not Found: react-native-calendar-heatmap@latest`

`error Couldn't find package "react-native-calendar-heatmap" on the "npm" registry.`

**Comment by ayooby** [comment]
@lefrenk Thank you for you kindness.
I've updated npm installation in Readme
