### ISSUE TITLE
Touchable Opacity and Hint in rectangular box of heat map

### ISSUE THREAD

**Issue by GowthamGr** [ayooby/react-native-calendar-heatmap#4]
Hi @ayooby ,
       I used this example in my application how to add touchable opacity,hint and zoomable animations in the heat map

**Comment by ayooby** [comment]
Hi @GowthamGr,
Sorry for being late to answer your issue.
I'll send you solution ASAP

**Comment by ayooby** [comment]
@GowthamGr you can pass `Onpress` property 
```
        <CalendarHeatmap
          endDate={new Date('2016-04-01')}
          numDays={100}
          onPress={(index) => console.log('index of ', index)} //log pressed rectangle index
          values={[
            { date: '2016-01-01' },
            { date: '2016-01-22' },
            { date: '2016-01-30' },
          ]}
        />
```
hint, zoomable animation are not this package features.
