### ISSUE TITLE
Invariant Violation: requireNativeComponent "RNSVGSpan" was not found in the UIManager

### ISSUE THREAD

**Issue by mrded** [ayooby/react-native-calendar-heatmap#5]
I tried to apply following module to a vanila react-native project. On load I'm getting following error:

> Invariant Violation: requireNativeComponent "RNSVGSpan" was not found in the UIManager

- react: 16.6.1
- react-native: 0.57.7
- react-native-calendar-heatmap: 0.1.2

Please let me know if you need more info.

![simulator screen shot - iphone xr - 2018-12-23 at 18 21 02](https://user-images.githubusercontent.com/347098/50386548-bde73d00-06e0-11e9-8423-ed0f44080e37.png)

**Comment by ayooby** [comment]
@mrded 
thanks for opening the issue.
I'll look at this error asap.


Happy new year 🎉

**Comment by mrded** [comment]
Thanks for a quick response. It may be worth mentioning that the package is depending on`react-native-svg`. You need to install it properly with `react-native link react-native-svg`.

Merry Xmas and happy new year!

**Comment by ayooby** [comment]
@mrded you were totally right. I've updated Readme file, package installation needs an extra linking step.
